### PR TITLE
Remove flutter_custom_tabs

### LINKED ISSUE #1069: Replace flutter_custom_tabs with webview_flutter or url_launcher
**Describe the bug**
flutter_custom_tabs does basically the same thing as url_launcher

### PR DESCRIPTION
**Pull request by LouisPhilippeHeon**
### ⁉️ Related Issue
Closes #1069 

## 📖 Description
Removed dependency

### 🧪 How Has This Been Tested?
Manual tests, iOS and Android

### ☑️ Checklist before requesting a review
- [X] I have performed a self-review of my code.
- [X] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [X] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`.

### CODE REVIEW

File: lib/features/schedule/schedule_view.dart [hunk 1]
```diff
@@ -323,16 +327,20 @@ class _ScheduleViewState extends State<ScheduleView>
...
           ),
-          rightIcon: Icon(
-            Icons.chevron_right,
-            size: 30,
-            color: chevronColor,
-          )),
+        ),
+        rightIconConfig: calendar_view.IconDataConfig(
+          icon: (context) => Icon(
+              Icons.chevron_left,
```
Comment (XavierPaquet-Rapold) [inline lib/features/schedule/schedule_view.dart:339]: Ce serait pas ?
```suggestion
              Icons.chevron_right,
```

File: lib/features/schedule/schedule_view.dart [hunk 2]
```diff
@@ -238,15 +238,19 @@ class _ScheduleViewState extends State<ScheduleView>
...
+                color: chevronColor
+            ),
           ),
-          rightIcon: Icon(
-            Icons.chevron_right,
-            size: 30,
-            color: chevronColor,
+          rightIconConfig: calendar_view.IconDataConfig(
+            icon: (context) => Icon(
+                Icons.chevron_left,
```
Comment (XavierPaquet-Rapold) [inline lib/features/schedule/schedule_view.dart:250]: Ce serait pas ?
```suggestion
                Icons.chevron_right,
```

**Review by XavierPaquet-Rapold — APPROVED** [review]

**Review by EffBureau — APPROVED** [review]
LGTM 🤓
