### PR TITLE
Fixed empty schedule on sundays

### LINKED ISSUE #1127: Default schedule is always empty when viewing on Sunday
**Describe the bug**
Anytime you the user attempts to view the default schedule of a semester on a Sunday, an empty calendar is returned. Regardless of the semester.

**To Reproduce**
1. Ensure the day is a Sunday
2. Click on the default schedule button on the `Student` page

Alternatively, you can mock this behaviour by changing the date to a Sunday via the device's settings.

**Expected behavior**
The correct schedule should be returned just like any other day of the week.

**Screenshots**
Screenshot_1736831835

**Smartphone (please complete the following information):**
 - Device: Pixel 9 Pro
 - OS: Android 15
 - Browser: Chrome
 - Version: 4.56.0

### PR DESCRIPTION
**Pull request by DylanApardian**
### ⁉️ Related Issue

Closes #1127 

## 📖 Description

The issue is because `.weekday` returns the weekday index with Monday (1) being the first day and Sunday (7) being the last.
When we try to calculate `daysToAdd` on a Sunday, we're doing `eventData.dayOfTheWeek - 7`.
For example if we have an event on Monday, the calculation will be `daysToAdd = 1 - 7`.
Because of this, the `targetDate` becomes `-6` (6 days in the past).
Since the date is in the past, it doesn't get show on the calendar because the default calendar only displays the current week.

I decided to create a method to return `0` as the index for Sunday instead of `7`.
I'm open to other solutions, I feel like this is the simplest solution at the moment.

### 🧪 How Has This Been Tested?
- Manual testing (changed the device's current date to all days of the week)
- Ran the unit tests

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`.

### CODE REVIEW

File: lib/features/schedule/schedule_default/schedule_default_viewmodel.dart [hunk 1]
```diff
@@ -79,6 +79,11 @@ class ScheduleDefaultViewModel
     return courseColors[courseName];
   }
 
+  int getWeekDayIndex(DateTime dateTime) {
+    int weekday = dateTime.weekday;
+    return weekday == 7 ? 0 : weekday;
```
Comment (XavierPaquet-Rapold) [inline lib/features/schedule/schedule_default/schedule_default_viewmodel.dart:84]:
```suggestion
    return weekday % 7;
```

**Review by XavierPaquet-Rapold — CHANGES_REQUESTED** [review]

File: lib/features/schedule/schedule_default/schedule_default_viewmodel.dart (hunk 1 above)
Comment (LouisPhilippeHeon) [reply lib/features/schedule/schedule_default/schedule_default_viewmodel.dart:84]: Rendu là on peut enlever la méthode et le faire inline

Comment (DylanApardian) [reply lib/features/schedule/schedule_default/schedule_default_viewmodel.dart]: Done

**Review by XavierPaquet-Rapold — APPROVED** [review]

**Review by LouisPhilippeHeon — APPROVED** [review]
