### PR TITLE
Bug/#1155 week viewmodel test

### LINKED ISSUE #1155: [Bug] week_viewmodel_test not returning to current date
**Describe the bug**
Week_viewmodel test not passing when the date is Sunday :

 /home/runner/work/Notre-Dame/Notre-Dame/test/ui/schedule/view_model/calendar/week_viewmodel_test.dart: return to current date does not update weekSelected (failed)
  Expected: <false>
    Actual: <true>
  
  package:matcher                                                     expect
  package:flutter_test/src/widget_tester.dart 480:18                  expect
Error: 400 tests passed, 1 failed.

**To Reproduce**
1. Set your date on your machine to Sunday
2. Run the tests

**Expected behavior**
The calendar is supposed to move you to the next week if your date is on the Sundays, 
unless you have a course on a Sunday. Which the test doesn't check. 

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Ethan-Estrada**
### ⁉️ Related Issue

Closes #1155
## 📖 Description

Fixed week_viewmodel_test.dart.
Added a new utils to get current Sunday.
### 🧪 How Has This Been Tested?

Added a new list of CourseActivity's with the date set to Sundays to the test, in order to mock the behaviour of the week_viewmodel returnToCurrentDate function.
Tested while manually changing the date on my computer.

### ☑️ Checklist before requesting a review
- [x ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [x ] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`.

### CODE REVIEW

File: lib/utils/utils.dart [hunk 1]
```diff
@@ -23,6 +23,11 @@ mixin Utils {
         .withoutTime;
   }
 
+  static DateTime getCurrentSundayOfWeek(DateTime currentDate) {
```
Comment (LouisPhilippeHeon) [inline lib/utils/utils.dart:26]: Vu que ça sert juste pour un test on ne devrait pas le mettre dans les utils

Comment (LouisPhilippeHeon) [reply lib/utils/utils.dart:26]: Sinon tu peux utiliser la méthode pour obtenir le premier jour de la semaine et ajouter 6 jour pour avoir le samedi

**Review by LouisPhilippeHeon — CHANGES_REQUESTED** [review]

**Review by LouisPhilippeHeon — APPROVED** [review]

**Review by XavierPaquet-Rapold — APPROVED** [review]
