### PR TITLE
Bugfix - Schedule isn't displayed if there is no activities available

### LINKED ISSUE #46: [Schedule] Session is active but don't have any activities/courses
**Describe the bug**
As a student, if I'm registered for an internship and don't have any courses the app can't load my courses (and activities).

**To Reproduce**
Need to be registered for an internship and don't have any courses for the same session as the internship.

**Expected behavior**
I should be able to see my schedule and grades.

### PR DESCRIPTION
**Pull request by apomalyn**
For example, if you are registered for an internship but don't have any courses at the same session, Signets return an error (no schedule available).
Now we will have a simple handler for the Signets errors. Because Signets doesn't have very detailed documentation, it's very possible that some errors aren't handled right now. If you spot an error not handled, please add it :wink: 

Will close #46

### CODE REVIEW

File: lib/core/constants/signets_errors.dart [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+  static const String credentialsInvalid = "Code d'accès ou mot de passe invalide";
+
+  /// Error message returned when the schedule isn't ready or the session is too
+  /// old to be saved on the system
+  static const String scheduleNotAvailable = "Aucune donnée.  Cela peut être "
+      "causé parce que l'horaire détaillé n'est pas encore finalisé (il l'est "
+      "généralement quelques jours avant le début de la session), ou parce que "
+      "l'horaire est trop ancien (nous ne gardons que 4 sessions), ou que vous "
+      "n'êtes pas inscrit, ou que vous n'êtes inscrit qu'à des activité sans "
```
Comment (camillebrulotte) [inline lib/core/constants/signets_errors.dart:12]:
```suggestion
      "n'êtes pas inscrit, ou que vous n'êtes inscrit qu'à des activités sans "
```

File: lib/core/constants/signets_errors.dart [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+      "horaire, comme un stage ou que que vous êtes en rédaction de mémoire "
```
Comment (camillebrulotte) [inline lib/core/constants/signets_errors.dart:13]:
```suggestion
      "horaire, comme un stage ou que vous êtes en rédaction de mémoire "
```

File: lib/core/services/signets_api.dart [hunk 3]
```diff
@@ -256,15 +257,23 @@ class SignetsApi {
...
     if (responseBody
         .findElements(_signetsErrorTag)
         .first
         .innerText
         .isNotEmpty) {
-      throw ApiException(
-          prefix: tagError,
-          message: responseBody.findElements(_signetsErrorTag).first.innerText);
+      switch (responseBody.findElements(_signetsErrorTag).first.innerText) {
+        case SignetsError.scheduleNotAvailable:
```
Comment (camillebrulotte) [inline lib/core/services/signets_api.dart:267]: Il semble rentrer dans le "default" et non dans le case SignetsError.sceduleNotAvailable.

J'ai l'impression que le texte dans _responseBody.findElements(_signetsErrorTag).first.innerText_ n'est pas le même que dans 'SignetsError.scheduleNotAvailable'. Quand je change la constante scheduleNotAvailable il semble bien fonctionner :) 

J'ai print ce qu'il y a dans les deux textes et il y a des petites différence :) 
image

File: lib/core/constants/signets_errors.dart (hunk 2 above)
Comment (AlexandreMarkus) [reply lib/core/constants/signets_errors.dart:13]: même chose ici

File: lib/core/constants/signets_errors.dart (hunk 1 above)
Comment (apomalyn) [reply lib/core/constants/signets_errors.dart:12]: Exact :)

File: lib/core/services/signets_api.dart (hunk 3 above)
Comment (apomalyn) [reply lib/core/services/signets_api.dart:267]: And this is why we would like an error code and no very long string XD

Comment (apomalyn) [reply lib/core/services/signets_api.dart:267]: I suggest two solutions:
1. We reverse the problem and instead of considering some error non-blocking (scheduleNotAvailable) and everything else blocking we can consider some error blocking (credentialsInvalid) and everything else non-blocking.
2. We can add the female version of the error in SignetsError and add it into the switch case.

I prefer solution 2. personally because we have more control over the errors but what do you think?

Comment (camillebrulotte) [reply lib/core/services/signets_api.dart:267]: Yes je suis d'accord avec l'option 2 :D

File: android/settings.gradle [hunk 4]
```diff
@@ -13,3 +13,16 @@ localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }
...
+def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
+if (pluginsFile.exists()) {
+    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
+}
+
+plugins.each { name, path ->
+    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
+    include ":$name"
+    project(":$name").projectDir = pluginDirectory
+}
```
[the remark this answers is not in the document]
Comment (apomalyn) [reply android/settings.gradle:28]: *Beep* this is coming from the PR with grades backend --' I removing that ASAP

File: lib/core/services/signets_api.dart (hunk 3 above)
Comment (AlexandreMarkus) [reply lib/core/services/signets_api.dart:267]: Solution 2 for me also

**Review by AlexandreMarkus — APPROVED** [review]
different error message based on gender :laughing:
