### PR TITLE
Bugfix/theme and locale

### LINKED ISSUE #61: Theme in settings does not work well
**Describe the bug**
The theme does not stay when destroying the app process.

**To Reproduce**
1. Go to More
2. Go to Settings
3. Click on Theme
4. Select Dark (if the default theme of the phone is light) _or_ Select Light (if the default theme of the phone is dark)
5. Quit the app
6. Launch the app
7. Go to More
8. Go to Settings

**Expected behavior**
The app should keep the theme color of the theme selected in Settings.

**Screenshots**

https://user-images.githubusercontent.com/37625944/110405935-65957f00-804f-11eb-935e-d09636ee4810.mp4

### PR DESCRIPTION
**Pull request by AlexandreMarkus**
Close #61

### CODE REVIEW

**Review by camillebrulotte — COMMENTED** [review]
Hmm the app doesn't seem to work anymore when i launch it on IOS (in Dark and Light theme). It only shows a white screen. 

Capture d’écran, le 2021-03-11 à 19 30 50

```
2021-03-11 19:36:11.341343-0500 Runner[29292:487151] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
2021-03-11 19:36:11.893275-0500 Runner[29292:485631] Metal GPU Frame Capture Enabled
2021-03-11 19:36:11.893956-0500 Runner[29292:485631] Metal API Validation Enabled
2021-03-11 19:36:12.093521-0500 Runner[29292:485631] ((null)) was false: provideAPIKey: requires non-empty API key
2021-03-11 19:36:12.115557-0500 Runner[29292:485631] [Firebase/Crashlytics] Version 7.3.0
2021-03-11 19:36:12.223825-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
2021-03-11 19:36:12.235886-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'ca.etsmtl.applets.notredame'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2021-03-11 19:36:12.274164-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023007] Analytics v.7.3.0 started
2021-03-11 19:36:12.276736-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-03-11 19:36:12.428459-0500 Runner[29292:487188] 7.3.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings. If this is your first time launching the app, make sure you have enabled Crashlytics in the Firebase Console. Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
2021-03-11 19:36:12.684219-0500 Runner[29292:487163] 7.3.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-03-11 19:36:12.931671-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2021-03-11 19:36:12.932563-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
2021-03-11 19:36:13.277067-0500 Runner[29292:487212] flutter: Observatory listening on http://127.0.0.1:59012/yKvrq7NOD88=/
2021-03-11 19:36:16.141770-0500 Runner[29292:487201] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      SettingsManager.fetchLanguageAndThemeMode (package:notredame/core/managers/settings_manager.dart:47:40)
<asynchronous suspension>
#2      main (package:notredame/main.dart:34:3)
<asynchronous suspension>

```

**Comment by AlexandreMarkus** [comment]
> Hmm the app doesn't seem to work anymore when i launch it on IOS (in Dark and Light theme). It only shows a white screen.
> 
> Capture d’écran, le 2021-03-11 à 19 30 50
> 
> ```
> 2021-03-11 19:36:11.341343-0500 Runner[29292:487151] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
> 2021-03-11 19:36:11.893275-0500 Runner[29292:485631] Metal GPU Frame Capture Enabled
> 2021-03-11 19:36:11.893956-0500 Runner[29292:485631] Metal API Validation Enabled
> 2021-03-11 19:36:12.093521-0500 Runner[29292:485631] ((null)) was false: provideAPIKey: requires non-empty API key
> 2021-03-11 19:36:12.115557-0500 Runner[29292:485631] [Firebase/Crashlytics] Version 7.3.0
> 2021-03-11 19:36:12.223825-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
> 2021-03-11 19:36:12.235886-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'ca.etsmtl.applets.notredame'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
> 2021-03-11 19:36:12.274164-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023007] Analytics v.7.3.0 started
> 2021-03-11 19:36:12.276736-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> 2021-03-11 19:36:12.428459-0500 Runner[29292:487188] 7.3.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings. If this is your first time launching the app, make sure you have enabled Crashlytics in the Firebase Console. Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
> 2021-03-11 19:36:12.684219-0500 Runner[29292:487163] 7.3.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
> 2021-03-11 19:36:12.931671-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
> 2021-03-11 19:36:12.932563-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
> 2021-03-11 19:36:13.277067-0500 Runner[29292:487212] flutter: Observatory listening on http://127.0.0.1:59012/yKvrq7NOD88=/
> 2021-03-11 19:36:16.141770-0500 Runner[29292:487201] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
> #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
> #1      SettingsManager.fetchLanguageAndThemeMode (package:notredame/core/managers/settings_manager.dart:47:40)
> <asynchronous suspension>
> #2      main (package:notredame/main.dart:34:3)
> <asynchronous suspension>
> ```

I only tested it on Android, and it seems to work fine. Are you able to confirm that this behaviour is only happening on IOS? Can you try it on Android

**Comment by camillebrulotte** [comment]
> > Hmm the app doesn't seem to work anymore when i launch it on IOS (in Dark and Light theme). It only shows a white screen.
> > Capture d’écran, le 2021-03-11 à 19 30 50
> > ```
> > 2021-03-11 19:36:11.341343-0500 Runner[29292:487151] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
> > 2021-03-11 19:36:11.893275-0500 Runner[29292:485631] Metal GPU Frame Capture Enabled
> > 2021-03-11 19:36:11.893956-0500 Runner[29292:485631] Metal API Validation Enabled
> > 2021-03-11 19:36:12.093521-0500 Runner[29292:485631] ((null)) was false: provideAPIKey: requires non-empty API key
> > 2021-03-11 19:36:12.115557-0500 Runner[29292:485631] [Firebase/Crashlytics] Version 7.3.0
> > 2021-03-11 19:36:12.223825-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
> > 2021-03-11 19:36:12.235886-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'ca.etsmtl.applets.notredame'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
> > 2021-03-11 19:36:12.274164-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023007] Analytics v.7.3.0 started
> > 2021-03-11 19:36:12.276736-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> > 2021-03-11 19:36:12.428459-0500 Runner[29292:487188] 7.3.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings. If this is your first time launching the app, make sure you have enabled Crashlytics in the Firebase Console. Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
> > 2021-03-11 19:36:12.684219-0500 Runner[29292:487163] 7.3.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
> > 2021-03-11 19:36:12.931671-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
> > 2021-03-11 19:36:12.932563-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
> > 2021-03-11 19:36:13.277067-0500 Runner[29292:487212] flutter: Observatory listening on http://127.0.0.1:59012/yKvrq7NOD88=/
> > 2021-03-11 19:36:16.141770-0500 Runner[29292:487201] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
> > #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
> > #1      SettingsManager.fetchLanguageAndThemeMode (package:notredame/core/managers/settings_manager.dart:47:40)
> > <asynchronous suspension>
> > #2      main (package:notredame/main.dart:34:3)
> > <asynchronous suspension>
> > ```
> 
> I only tested it on Android, and it seems to work fine. Are you able to confirm that this behaviour is only happening on IOS? Can you try it on Android @camillebrulotte

It crashes at that line on Android and I only see a white screen too :
image

```
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> lib\main.dart:1
> √ Built build\app\outputs\flutter-apk\app-debug.apk.
> I/Choreographer(20672): Skipped 47 frames!  The application may be doing too much work on its main thread.
> Connecting to VM Service at ws://127.0.0.1:49286/JhPxcD6p4aI=/ws
> D/EGL_emulation(20672): eglMakeCurrent: 0xeed7ff40: ver 3 0 (tinfo 0xdbc0fb50)
> D/eglCodecCommon(20672): setVertexArrayObject: set vao to 0 (0) 1 0
> E/flutter (20672): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
> E/flutter (20672): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
> E/flutter (20672): #1      SettingsManager.fetchLanguageAndThemeMode
> package:notredame/…/managers/settings_manager.dart:47
> E/flutter (20672): <asynchronous suspension>
> E/flutter (20672): #2      main
> package:notredame/main.dart:34
> E/flutter (20672): <asynchronous suspension>
> E/flutter (20672):
```

**Comment by AlexandreMarkus** [comment]
> > > Hmm the app doesn't seem to work anymore when i launch it on IOS (in Dark and Light theme). It only shows a white screen.
> > > Capture d’écran, le 2021-03-11 à 19 30 50
> > > ```
> > > 2021-03-11 19:36:11.341343-0500 Runner[29292:487151] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
> > > 2021-03-11 19:36:11.893275-0500 Runner[29292:485631] Metal GPU Frame Capture Enabled
> > > 2021-03-11 19:36:11.893956-0500 Runner[29292:485631] Metal API Validation Enabled
> > > 2021-03-11 19:36:12.093521-0500 Runner[29292:485631] ((null)) was false: provideAPIKey: requires non-empty API key
> > > 2021-03-11 19:36:12.115557-0500 Runner[29292:485631] [Firebase/Crashlytics] Version 7.3.0
> > > 2021-03-11 19:36:12.223825-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
> > > 2021-03-11 19:36:12.235886-0500 Runner[29292:487151] 7.3.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'ca.etsmtl.applets.notredame'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
> > > 2021-03-11 19:36:12.274164-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023007] Analytics v.7.3.0 started
> > > 2021-03-11 19:36:12.276736-0500 Runner[29292:487151] 7.3.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> > > 2021-03-11 19:36:12.428459-0500 Runner[29292:487188] 7.3.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings. If this is your first time launching the app, make sure you have enabled Crashlytics in the Firebase Console. Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
> > > 2021-03-11 19:36:12.684219-0500 Runner[29292:487163] 7.3.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
> > > 2021-03-11 19:36:12.931671-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
> > > 2021-03-11 19:36:12.932563-0500 Runner[29292:487162] 7.3.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
> > > 2021-03-11 19:36:13.277067-0500 Runner[29292:487212] flutter: Observatory listening on http://127.0.0.1:59012/yKvrq7NOD88=/
> > > 2021-03-11 19:36:16.141770-0500 Runner[29292:487201] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
> > > #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
> > > #1      SettingsManager.fetchLanguageAndThemeMode (package:notredame/core/managers/settings_manager.dart:47:40)
> > > <asynchronous suspension>
> > > #2      main (package:notredame/main.dart:34:3)
> > > <asynchronous suspension>
> > > ```
> > 
> > 
> > I only tested it on Android, and it seems to work fine. Are you able to confirm that this behaviour is only happening on IOS? Can you try it on Android @camillebrulotte
> 
> It crashes at that line on Android and I only see a white screen too :
> image
> 
> ```
> > Launching lib\main.dart on Android SDK built for x86 in debug mode...
> > lib\main.dart:1
> > √ Built build\app\outputs\flutter-apk\app-debug.apk.
> > I/Choreographer(20672): Skipped 47 frames!  The application may be doing too much work on its main thread.
> > Connecting to VM Service at ws://127.0.0.1:49286/JhPxcD6p4aI=/ws
> > D/EGL_emulation(20672): eglMakeCurrent: 0xeed7ff40: ver 3 0 (tinfo 0xdbc0fb50)
> > D/eglCodecCommon(20672): setVertexArrayObject: set vao to 0 (0) 1 0
> > E/flutter (20672): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
> > E/flutter (20672): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
> > E/flutter (20672): #1      SettingsManager.fetchLanguageAndThemeMode
> > package:notredame/…/managers/settings_manager.dart:47
> > E/flutter (20672): <asynchronous suspension>
> > E/flutter (20672): #2      main
> > package:notredame/main.dart:34
> > E/flutter (20672): <asynchronous suspension>
> > E/flutter (20672):
> ```
 @camillebrulotte 
Should be good now!!! It was happening when the preferenceService was not initialized

**Comment by JonathanDuvalV** [comment]
Tried it on Android, it works great! But I can't get it to work either on iOS.

**Review by camillebrulotte — APPROVED** [review]
It works well on Android and IOS for me now ! Nice :D

**Comment by JonathanDuvalV** [comment]
Also got it to work on iOS now. I had problems locally with the SDK.

**Comment by apomalyn** [comment]
I found some issues :) 

https://user-images.githubusercontent.com/22211097/110888759-d9878f80-82ba-11eb-8abc-3505aab79eba.mov

As you can see, if I change the language the theme doesn't switch to "dark" 😄  and that will be until I restart the application.

Also:
https://user-images.githubusercontent.com/22211097/110889048-6af70180-82bb-11eb-98a8-e1859840c1e7.mov

As you can see, if I log out of the application, and log back in, my preferences are still set. The correct behaviour should that when a user log out, all his/her preferences are erased.

Could you fix that, please? 😄

**Comment by apomalyn** [comment]
Also, when a user opens the application for the first time, there is no locale or theme set, which create an error:

Screen Shot 2021-03-11 at 11 19 57 PM

Step to reproduce:
1. Log out of the application
2. Uninstall the app from the device
3. Re run flutter.

**Comment by AlexandreMarkus** [comment]
> I found some issues :) 
> 
> https://user-images.githubusercontent.com/22211097/110888759-d9878f80-82ba-11eb-8abc-3505aab79eba.mov
> 
> As you can see, if I change the language the theme doesn't switch to "dark" 😄  and that will be until I restart the application.
> 
> Also:
> 
> https://user-images.githubusercontent.com/22211097/110889048-6af70180-82bb-11eb-98a8-e1859840c1e7.mov
> 
> As you can see, if I log out of the application, and log back in, my preferences are still set. The correct behaviour should that when a user log out, all his/her preferences are erased.
> 
> Could you fix that, please? 😄 
> 
> 

The first issue appens since we pass the AppIntl to the Viewmodel. Actually if you press back, then reopen the settings the Viewmodel will get rebuilt and it should be good. Is there a way to trigger the build of the Viewmodel?

**Review by apomalyn — COMMENTED** [review]
> ...
> The first issue appens since we pass the AppIntl to the Viewmodel. Actually if you press back, then reopen the settings the Viewmodel will get rebuilt and it should be good. Is there a way to trigger the build of the Viewmodel?

OK, I found the solution. The problem is that you treat the theme (coming from settings manager) as a String but it's an enumeration! :D If you modify your viewmodel to use ThemeMode and not a String, and adjust the settings view everything should be functional 😄  

(if my explanations aren't clear, tell me 😅 )

**Comment by AlexandreMarkus** [comment]
> Also, when a user opens the application for the first time, there is no locale or theme set, which create an error:
> 
> Screen Shot 2021-03-11 at 11 19 57 PM
> 
> Step to reproduce:
> 
> 1. Log out of the application
> 2. Uninstall the app from the device
> 3. Re run flutter.

done!

**Comment by AlexandreMarkus** [comment]
> I found some issues :)
> 
>  Screen.Recording.2021-03-11.at.10.40.44.PM.mov 
> As you can see, if I change the language the theme doesn't switch to "dark"  and that will be until I restart the application.
> 
> Also:
> 
>  Screen.Recording.2021-03-11.at.10.43.49.PM.mov 
> As you can see, if I log out of the application, and log back in, my preferences are still set. The correct behaviour should that when a user log out, all his/her preferences are erased.
> 
> Could you fix that, please?

first issue is done!
second one should be good too, need to check on IOS

**Comment by camillebrulotte** [comment]
> > I found some issues :)
> > Screen.Recording.2021-03-11.at.10.40.44.PM.mov
> > As you can see, if I change the language the theme doesn't switch to "dark"  and that will be until I restart the application.
> > Also:
> > Screen.Recording.2021-03-11.at.10.43.49.PM.mov
> > As you can see, if I log out of the application, and log back in, my preferences are still set. The correct behaviour should that when a user log out, all his/her preferences are erased.
> > Could you fix that, please?
> 
> first issue is done!
> second one should be good too, need to check on IOS

Maybe I don't fully understand the issue, but is it normal that for example : 

*The phone is set with light mode*
1- I set "Dark" in the app settings
2- I log out
3- I log back in

"System" still shows a dark theme even after logging out and then, when I click on "System", the app becomes in light theme. 
Isn't it supposed to already be in light theme when I log back in, in that case ?
There is the same behavior on IOS.

https://user-images.githubusercontent.com/37625944/111040562-73595480-8401-11eb-96c1-9b10531bd2fb.mp4

**Comment by camillebrulotte** [comment]
> > Also, when a user opens the application for the first time, there is no locale or theme set, which create an error:
> > Screen Shot 2021-03-11 at 11 19 57 PM
> > Step to reproduce:
> > 
> > 1. Log out of the application
> > 2. Uninstall the app from the device
> > 3. Re run flutter.
> 
> done!

Nice ! :D It doesn't seem to crash when I uninstall the app and re run flutter

**Comment by AlexandreMarkus** [comment]
> > > I found some issues :)
> > > Screen.Recording.2021-03-11.at.10.40.44.PM.mov
> > > As you can see, if I change the language the theme doesn't switch to "dark"  and that will be until I restart the application.
> > > Also:
> > > Screen.Recording.2021-03-11.at.10.43.49.PM.mov
> > > As you can see, if I log out of the application, and log back in, my preferences are still set. The correct behaviour should that when a user log out, all his/her preferences are erased.
> > > Could you fix that, please?
> > 
> > 
> > first issue is done!
> > second one should be good too, need to check on IOS
> 
> Maybe I don't fully understand the issue, but is it normal that for example :
> 
> _The phone is set with light mode_
> 1- I set "Dark" in the app settings
> 2- I log out
> 3- I log back in
> 
> "System" still shows a dark theme even after logging out and then, when I click on "System", the app becomes in light theme.
> Isn't it supposed to already be in light theme when I log back in, in that case ?
> There is the same behavior on IOS.
> 
>  Theme.mp4

Should be fix with the latest commit

File: lib/core/managers/settings_manager.dart [hunk 1]
```diff
@@ -39,11 +39,20 @@ class SettingsManager with ChangeNotifier {
     return _themeMode;
   }
 
+  /// Get Locale and Theme to init app with
+  Future<void> fetchLanguageAndThemeMode() async {
+    final theme = await _preferencesService.getString(PreferencesFlag.theme);
+    _themeMode = ThemeMode.values.firstWhere((e) => e.toString() == theme);
+    final lang = await _preferencesService.getString(PreferencesFlag.locale);
+    _locale = AppIntl.supportedLocales.firstWhere((e) => e.toString() == lang);
+    return;
```
[the remark this answers is not in the document]
Comment (AlexandreMarkus) [reply lib/core/managers/settings_manager.dart]: done

File: lib/core/managers/settings_manager.dart [hunk 2]
```diff
@@ -39,11 +39,25 @@ class SettingsManager with ChangeNotifier {
     return _themeMode;
   }
 
+  /// Get Locale and Theme to init app with
+  Future<void> fetchLanguageAndThemeMode() async {
+    final theme = await _preferencesService.getString(PreferencesFlag.theme);
+    if (theme != null) {
+      _themeMode = ThemeMode.values.firstWhere((e) => e.toString() == theme);
```
[the remark this answers is not in the document]
Comment (AlexandreMarkus) [reply lib/core/managers/settings_manager.dart:54]: I think it is needed by the ChangeNotifier service. If I use a local variable instead, the main does not receive the infos and apply the wanted theme and locale

**Comment by camillebrulotte** [comment]
@apomalyn 

When i logout on IOS, it shows :
```
2021-03-20 11:46:36.079522-0400 Runner[67998:1743837] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/Users/camillebrulotte/Library/Developer/CoreSimulator/Devices/3370171F-E666-4866-9952-51694FB5B0B8/data/Containers/Data/Application/85C98B63-BC5E-4EF0-A3EE-5ED69745E0F9/Library/Caches/ETSMobileCache/f075f330-8774-11eb-b768-05ecdca60c31.file' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#8      _rootRun (dart:async/zone.dart:1354:13)
#9      _CustomZone.run (dart:async/zone.dart:1258:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Or else, everything seems to work the same way as on Android.

File: lib/core/viewmodels/more_viewmodel.dart [hunk 3]
```diff
@@ -66,11 +71,15 @@ class MoreViewModel extends FutureViewModel {
     } on Exception catch (e) {
       onError(e);
     }
-    UserRepository().logOut();
+    await PreferencesService().clear();
+    await UserRepository().logOut();
+
```
Comment (apomalyn) [inline lib/core/viewmodels/more_viewmodel.dart:76]: It also necessary to invalidate the contents of CourseRepository.coursesActivity and sessions. A simple clear should be enough :sweat_smile:

**Review by apomalyn — CHANGES_REQUESTED** [review]
A single test to add and that will be good! :D

**Comment by apomalyn** [comment]
> @apomalyn
> 
> When i logout on IOS, it shows :
> 
> ```
> 2021-03-20 11:46:36.079522-0400 Runner[67998:1743837] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/Users/camillebrulotte/Library/Developer/CoreSimulator/Devices/3370171F-E666-4866-9952-51694FB5B0B8/data/Containers/Data/Application/85C98B63-BC5E-4EF0-A3EE-5ED69745E0F9/Library/Caches/ETSMobileCache/f075f330-8774-11eb-b768-05ecdca60c31.file' (OS Error: No such file or directory, errno = 2)
> #0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
> #1      _rootRunUnary (dart:async/zone.dart:1362:47)
> #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
> #3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
> #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
> #5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
> #6      Future._completeWithValue (dart:async/future_impl.dart:539:5)
> #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
> #8      _rootRun (dart:async/zone.dart:1354:13)
> #9      _CustomZone.run (dart:async/zone.dart:1258:19)
> #10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
> #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
> #12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> ```
> 
> Or else, everything seems to work the same way as on Android.

I created an issue to find the source of the problem. For now, du to the nature of the application this bug isn't a priority.

File: lib/core/services/preferences_service.dart [hunk 4]
```diff
@@ -19,6 +18,12 @@ class PreferencesService {
     return prefs.setString(flag.toString(), value);
   }
 
+  Future<void> clear() async {
+    final SharedPreferences prefs = await SharedPreferences.getInstance();
+
+    await prefs.clear();
+  }
+
```
[the remark this answers is not in the document]
Comment (AlexandreMarkus) [reply lib/core/services/preferences_service.dart:26]: done

File: lib/core/viewmodels/more_viewmodel.dart (hunk 3 above)
Comment (AlexandreMarkus) [reply lib/core/viewmodels/more_viewmodel.dart:86]: done

**Review by apomalyn — CHANGES_REQUESTED** [review]
`more_viewmodel` doesn't have any test...I just so that :sweat_smile: this viewmodel handle the logout it's very important to test it

**Comment by MysticFragilist** [comment]
Okay, so I think I'm done! 😄 Let me know what you think @AlexandreMarkus and @apomalyn. Also, I had to refactor some part of your code, because it was really difficult to test so let me know if it's okay with you. In short, I pushed all the github functions (`createGithubIssue` and `uploadFileToGithub`) into a service called GithubApi. From there I was able to mock them. Furthermore, I pushed the `ShowToast` into the view because it was causing issue when the code was ran without a BuildContext as it were from a test.

PS: I couldn't test the "report a bug" because I don't have access to the repo for bug report. Could you test to see that everything work as before or give me access so I can test it?

**Comment by AlexandreMarkus** [comment]
> Okay, so I think I'm done!  Let me know what you think @AlexandreMarkus and @apomalyn. Also, I had to refactor some part of your code, because it was really difficult to test so let me know if it's okay with you. In short, I pushed all the github functions (`createGithubIssue` and `uploadFileToGithub`) into a service called GithubApi. From there I was able to mock them. Furthermore, I pushed the `ShowToast` into the view because it was causing issue when the code was ran without a BuildContext as it were from a test.
> 
> PS: I couldn't manually test the "report a bug" because I don't have access to the repo for bug report. Could you test to see that everything work as before or give me access so I can test it?
@MysticFragilist 
Sounds like a great idea! I will make the review later this week. I will show you (and everyone) how to test the "report a bug" on the coding session on Saturday.

File: test/viewmodels/more_viewmodel_test.dart [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+        await viewModel.logout();
+        expect(courseRepositoryMock.sessions.length, 0);
+        expect(courseRepositoryMock.coursesActivities.length, 0);
+      });
+
+      test('If the navigationService is rerouted to login', () async {
+        await viewModel.logout();
+        verify(navigationService.pop());
+        verify(navigationService.pushNamedAndRemoveUntil(RouterPaths.login));
+      });
```
Comment (apomalyn) [inline test/viewmodels/more_viewmodel_test.dart:142]: All of these could be one and only test. When you use `expect(...)` you can add a string as `reason:` (why this should be expected).

Also, we are missing some cases, what happens if the cache manager, settings manager, ... throw an error? 😄

File: lib/core/viewmodels/more_viewmodel.dart [hunk 6]
```diff
@@ -66,85 +81,37 @@ class MoreViewModel extends FutureViewModel {
     } on Exception catch (e) {
       onError(e);
     }
-    UserRepository().logOut();
+    await _preferencesService.clear();
+    await _userRepository.logOut();
+
+    settingsManager.resetLanguageAndThemeMode();
+    _courseRepository.sessions.clear();
+    _courseRepository.coursesActivities.clear();
```
Comment (apomalyn) [inline lib/core/viewmodels/more_viewmodel.dart:89]: Should also clear the `courses` content 😄

**Review by apomalyn — CHANGES_REQUESTED** [review]

File: lib/core/viewmodels/more_viewmodel.dart [hunk 7]
```diff
@@ -66,85 +81,37 @@ class MoreViewModel extends FutureViewModel {
...
     setBusy(false);
     // Dismiss alertDialog
     navigationService.pop();
     navigationService.pushNamedAndRemoveUntil(RouterPaths.login);
-    showToast(_appIntl.login_msg_logout_success);
+    settingsManager.notifyListeners();
```
Comment (apomalyn) [inline lib/core/viewmodels/more_viewmodel.dart:94]:
```suggestion
    notifyListeners();
```
We are in a viewmodel which is based on ChangeNotifier. Is there a reason for calling the notifyListeners of settingsManager?

Comment (MysticFragilist) [reply lib/core/viewmodels/more_viewmodel.dart:94]: I think it's to make sure the listeners of settings_manager aware that the language and the theme has been reset (so it fall back on system preference when login out). I'm not sure if we need to call the notifyListeners on the ViewModel, I try the two ways and everything works nonetheless. 
Perhaps, an idea to make it cleaner, would be to put the call to `settingsManager.notifyListeners` inside the function `settingsManager.resetLanguageAndThemeMode` so the logout doesn't know it's calling the notify.

What do you think @AlexandreMarkus ?

**Comment by MysticFragilist** [comment]
This PR will be pending, before the merging of #86 before being able to be finished. (Test needed using FlutterToast instead of OkToast)

File: lib/core/viewmodels/more_viewmodel.dart (hunk 7 above)
Comment (AlexandreMarkus) [reply lib/core/viewmodels/more_viewmodel.dart]: I think you would have to test it and see if it still does the same behavior

**Comment by AlexandreMarkus** [comment]
> This PR will be pending, until the #86 is merge. (Test needed using FlutterToast instead of OkToast)
@MysticFragilist 
Done!!

**Review by apomalyn — CHANGES_REQUESTED** [review]
Some little changes but otherwise it's good!!!!!

File: test/viewmodels/more_viewmodel_test.dart [hunk 8]
```diff
@@ -0,0 +1,207 @@
...
+  group('MoreViewModel - ', () {
+    setUp(() async {
+      cacheManagerMock = setupCacheManagerMock() as CacheManagerMock;
+      settingsManagerMock = setupSettingsManagerMock() as SettingsManagerMock;
+      courseRepositoryMock =
+          setupCourseRepositoryMock() as CourseRepositoryMock;
+      preferenceService = setupPreferencesServiceMock();
+      userRepositoryMock = setupUserRepositoryMock() as UserRepositoryMock;
+      navigationService = setupNavigationServiceMock();
+      githubApiMock = setupGithubApiMock() as GithubApiMock;
```
[the remark this answers is not in the document]
Comment (apomalyn) [reply test/viewmodels/more_viewmodel_test.dart:124]: No need to make all the changes for this PR :smile: We will create a issue with all the changes needed :smile:

File: README.fr.md [hunk 9]
```diff
@@ -42,6 +42,7 @@ chmod +x ./scripts/decrypt.sh
 ```
 flutter pub get
 ```
+## Ajouter la variable d'environnement pour GITHUB_API_KEY
```
[the remark this answers is not in the document]
Comment (AlexandreMarkus) [reply README.fr.md:45]: should have been removed with #72

Comment (AlexandreMarkus) [inline README.fr.md:45]:
```suggestion

```

**Comment by MysticFragilist** [comment]
I made sure to include your changes thanks guys 😄 Also, I created a new issue including the refactoring of the tests. I added some idea in there that could potentially be good for tests and some things to discuss. Feel free to let me know how you feel about thoses requests #96 😄!

If this PR is alright after your reviews, @AlexandreMarkus you can merge it directly, good job on the fix btw! 😄

**Review by apomalyn — APPROVED** [review]
LGTM !  🎉  🥇  🍾
